=== Rituraj2610/BridgeLabs/src/main/java/org/rituraj/json/data/practiceproblems/resources/Schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "name": {
        "type": "string"
      },
      "email": {
        "type": "string",
        "format": "email"
      },
      "department": {
        "type": "string"
      }
    },
    "required": ["id", "name", "email", "department"]
  }
}

=== Rituraj2610/BridgeLabs/src/main/java/org/rituraj/json/data/handson/resources/SampleData.json
[
  {
    "id": 1,
    "name": "John Doe",
    "email": "john.doe@example.com",
    "department": "Engineering"
  },
  {
    "id": 2,
    "name": "Jane Smith",
    "email": "jane.smith@example.com",
    "department": "Marketing"
  },
  {
    "id": 3,
    "name": "Michael Brown",
    "email": "michael.brown@example.com",
    "department": "Finance"
  },
  {
    "id": 4,
    "name": "Sophia Johnson",
    "email": "sophia.johnson@example.com",
    "department": "HR"
  }
]
